name: build_equals
version: 0.1.0-dev
description: >-
  TODO!
homepage: https://github.com/kevmoo/build_equals
environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  build: ^1.1.4
  build_config: ^0.4.0

  # Use a tight version constraint to ensure that a constraint on
  # `build_equals_annotation` properly constrains all features it provides.
  build_equals_annotation: '>=0.1.0 <0.1.1'
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.3.4
  build_verify: ^1.1.0
  source_gen_test: ^0.1.0
  test: ^1.6.0

dependency_overrides:
  build_equals_annotation:
    path: ../build_equals_annotation
